### ISSUE TITLE
Conflicts with TeemIP

### ISSUE THREAD

**Issue by yyri** [Molkobain/itop-datacenter-view#10]
Conflicts with latest TeemIP on iTop 2.7.1, some fields can not be added or deleted when setup

**Comment by Molkobain** [comment]
Hello @yyri ,

Can you give more details about your issue?
- Which version of molkobain-datacenter-view
- Which version of TeemIP, standalone or extension (which?)
- A screenshot of the error during the setup
- A extract of the /log/error.log file

Thanks,
Guillaume

**Comment by Molkobain** [comment]
Hello @yyri , any update?

**Comment by Molkobain** [comment]
Closing this issue as there is no news from @yyri .
