### ISSUE TITLE
Tab "Graphical view" shows only grayed fields

### ISSUE THREAD

**Issue by marcin-github** [Molkobain/itop-datacenter-view#19]
Hello!
I'm using:
itopl - 3.0.1
/molkobain-datacenter-view - 1.11.0
with nginx + php-fpm.
Tab "graphical view" displays only grayed squared and circles. Dev console shows that request 
`https://xxx/env-production/molkobain-datacenter-view/console/ajax.render.php?class=Rack&id=1680&operation=render_tab&edit_mode=`
gets http code 404. 
I turn on debug in config0itop.php:
```     'molkobain-datacenter-view' => array (
                'enabled' => true,
                'debug' => true,
[...]
```
but nothing new appeared in log/error.log. 
What could be a reason of this issue?

**Comment by Molkobain** [comment]
Hello Marcin,

If the request returns with a 404 HTTP code, it is most likely a web server configuration issue.
I'm not familiar with nginx but you should look that way.

Have you looked at the iTop error log just in case.

Cheers,
Guillaume

**Comment by marcin-github** [comment]
Hah, it was so obvious that I just ignored this 404. This behaviour was due tu implementing security tips from
https://www.itophub.io/wiki/page?id=3_0_0:install:security
Thank you!

**Comment by Molkobain** [comment]
Glad you fixed it!
Out of curiosity, which tip caused the issue?

**Comment by marcin-github** [comment]
`env-* : allow only files having one of those extensions : css|scss|js|map|png|bmp|gif|jpe?g|svg|tiff|woff2?|ttf|eot|html` 

so I didn't pass `.php` files to php interpreter.

**Comment by Molkobain** [comment]
Thanks for the feedback
