### ISSUE TITLE
TeemIp dependency fail?

### ISSUE THREAD

**Issue by Hipska** [Molkobain/itop-datacenter-view#20]
Hi,

In the TeemIp setup wizard, when unselecting the option "Data Center and Storage Devices", and selecting "Rack management from Molkobain", you get an error when running the final install:

> An exception occurred: Error loading module "molkobain-datacenter-view": /itop_design/classes/class[Rack] at line 116: could not be found - Loaded modules: dictionaries:1.0, core:1.0, application:1.0, authent-cas:3.0.3, authent-external:3.0.3, authent-ldap:3.0.3, authent-local:3.0.3, combodo-backoffice-darkmoon-theme:3.0.3, itop-attachments:3.0.3, itop-backup:3.0.3, itop-config:3.0.3, itop-files-information:3.0.3, itop-object-copier:1.4.3, itop-portal-base:3.0.3, itop-profiles-itil:3.0.3, itop-structure:3.0.3, itop-themes-compat:3.0.3, itop-tickets:3.0.3, itop-welcome-itil:3.0.3, molkobain-fontawesome5-pack:1.4.0, molkobain-handy-framework:1.8.0, molkobain-newsroom-provider:1.5.0, teemip-welcome:3.0.0, combodo-db-tools:3.0.3, email-reply:1.4.2, itop-config-mgmt:3.0.3, itop-core-update:3.0.3, itop-oauth-client:3.0.3, molkobain-console-tooltips:1.3.0, molkobain-datacenter-view:1.11.1 at line 966 in file /var/www/html/setup/modelfactory.class.inc.php

I think the module molkobain-datacenter-view is missing a dependency.

**Comment by Molkobain** [comment]
Hello Thomas,

Thanks for the feedback. I think this is related to a module/dependency change in iTop core. I'll fix it before iTop 3.1 release along with the other migration checks.

**Comment by Molkobain** [comment]
Actually it was an old bug, dependencies were all optional when they were actually mandatory.

As a quick fix I made them all mandatory, right solution would be to provide bridge modules for each, but I don't really have the bandwidth to make them / test them on the several iTop versions.

Thanks for pointing it out Thomas!
