### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by sskinnider** [Molkobain/itop-datacenter-view#5]
When installing on iTop v2.3.3.3159 error is thrown

![image](https://user-images.githubusercontent.com/25306327/59719075-8f5aa280-91e9-11e9-93e8-19b8b7b6e8d1.png)

Fatal error: Can't use method return value in write context in /var/www/html/itopdev2/env-production/molkobain-datacenter-view/common/datacenterview.class.inc.php on line 384

**Comment by Molkobain** [comment]
Hi!

Thanks for the feedback ! This might be due to your PHP version, I guess it's older than 5.6?

Can you tell which version of the extension you are trying to install and how you downloaded or? I'll see what I can do :)

**Comment by sskinnider** [comment]
Absolutely correct, I'm at 5.4.  Time to upgrade.  Thanks!

**Comment by Molkobain** [comment]
Actually, I just find that the extension must be compatible with iTop 2.4+ as one of its dependencies uses some functions that were introduced in iTop 2.4...

So the PHP 5.4 is not the only issue, you will have another after. I'm changing the extension documentation. Thanks for your help!

**Comment by Molkobain** [comment]
Release v1.3.1 (forcing iTop 2.4+) out! :)
