### ISSUE TITLE
Drag & Drop glitch

### ISSUE THREAD

**Issue by Krejza9** [Molkobain/itop-datacenter-view#7]
Hi, there's a glitch on Drag & Drop functionality.
On Chrome ver. 75.0.3770.100 and IE ver. 11
When you try to move component like server, switch,rack ,etc.
it does not rank to the Front and Rear container, but random on screen.
see. https://ibb.co/fnXyDKY

**Comment by Molkobain** [comment]
Hi @Krejza9 ,

I can't reproduce this on the demo on Chrome 75.0.3770.100. It might be a JS issue, could you do the following to check if there is any error in the JS console?

- Hit the *F12* key to open the dev. tools in Chrome
- Go to the *Console* tab of the dev. tools
- Refresh the page
- Drag a *Server*
- If the problem occurs, take a screenshot of the window including both the rack view and the JS console

Thanks!

**Comment by Krejza9** [comment]
Still same problem

https://ibb.co/sVPtxg0

https://ibb.co/RQNS70K

**Comment by Krejza9** [comment]
Hi , I found it.
There is a problem with top and left element on each draggable box, if you remove it, it will work correctly.

Before 
https://ibb.co/k6gF000
https://ibb.co/889F7dM


After
https://ibb.co/6tfC1MZ
https://ibb.co/WfkxbXg

**Comment by Molkobain** [comment]
Hi,

Actually this should be already taken care of, when dropped the CSS property `inset` is cleared on the element.

On your browser, seems like the `top` and `left` properties are set as well. Could you tell which version of Chrome you are using? Also which OS are you running, looks like MacOS?

I've updated the online demo with a hotfix, could try again? (You will need to clear you cache to get the new JS file)

Thanks! 🖖

**Comment by Krejza9** [comment]
Hi, I tested it, and record video with results.

https://youtu.be/lHDX3VysA34

I have both OS Windows 10 and MacOS.

**Comment by Molkobain** [comment]
This is insane, I just can't reproduce at all on latest Chrome, Firefox and IE11... I'm gonna try on another computer and get back to you.

Thank you very much for the video!

**Comment by Krejza9** [comment]
I tested on 5 PCs in our company, and still same problem.
I am glad that you created this product and I will be happy to buy it for our company and our customers, but first need fix this bug :)

**Comment by Molkobain** [comment]
Okay, after testing on Ubuntu, Windows 10, I finally reproduced it on my Win10 desktop on Chrome! Will try to fix it in the coming days and keep you updated. :)

**Comment by Molkobain** [comment]
For the record:
- NOT reproduced on Win10 1803 (17134.829) / Chrome 75.0.3770.100
- Reproduced on Win10 1809 (17763.615) / Chrome 75.0.3770.100

**Comment by Molkobain** [comment]
Ok, could you try again on the online demo? (Mind to clear your cache)
I made a hotfix that fixes it on my faulty desktop.

Thanks 🤞

**Comment by Krejza9** [comment]
It is fixed :)
thank you very much

**Comment by Molkobain** [comment]
Great, thank YOU for all the feedbacks! I updated the online demo and Molkobain I/O with the latest version.

Have a nice day
Guillaume
