### ISSUE TITLE
Blades in enclosure representation

### ISSUE THREAD

**Issue by AlexanderUzhinskiy** [Molkobain/itop-datacenter-view#9]
Hello! We are using your grate plugin but faces some issues. We have rack with 2 enclosures (2U). In each enclosure we have 8 blades. On the "graphical view" all the blades from enclosures are shown as "unmounted devices".

**Comment by Molkobain** [comment]
Hello @AlexanderUzhinskiy !

Can you share a screenshot of the whole "graphical view"?

Thanks 😀

**Comment by AlexanderUzhinskiy** [comment]
![1](https://user-images.githubusercontent.com/50914908/74655535-8ddce200-519d-11ea-93aa-2cb6d2ffad9e.jpg)
![2](https://user-images.githubusercontent.com/50914908/74655539-8f0e0f00-519d-11ea-9f0b-9a778413aab6.jpg)

Hello! Here they are.

**Comment by Molkobain** [comment]
By the look of your second screenshot, it's because you have not set the "position" attribute on the devices of the "dell-fx2s-1" enclosure. Just put a value on the devices you want to position and it will be alright :)

Just one thing, the enclosure seems to be only 2Us height so we won't be able to put them all in it. Is its height the right value?

**Comment by AlexanderUzhinskiy** [comment]
I tried to set the position to 6U wit or height but it does not help. 

Yes the height of the enclosure is 2U but 8 blades could be placed in it - that is the problem.

**Comment by Molkobain** [comment]
In the **free version** of the extension you can't have enclosure with a "grid" layout, meaning that you can't have multiple devices on the same row (eg. U number 6).

You need the **paid version** of the extension to handle that kind of enclosure. Take a look [here](https://github.com/Molkobain/itop-datacenter-view#complex-enclosures-support), the "complexe enclosure layout" chapter will give a good idea of what you can achieve. You can also try the online demo [here](http://mbc.itop.molkobain.com/pages/UI.php?operation=details&class=Rack&id=15&auth_user=admin&auth_pwd=admin#tabbedContent_0=8).

![](https://github.com/Molkobain/itop-datacenter-view/raw/develop/docs/mdv-profeatures-gridlayout-06.png)

Feel free to ask me if you ask any questions regarding this. 😊

**Comment by AlexanderUzhinskiy** [comment]
Now it is clear. Thank you!
